DELETE http://localhost:8080/events/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNoaWRpbm1hb251b3JhMTIzQGdtYWlsLmNvbSIsImV4cCI6MTcxODU3NTIzOSwidXNlcklkIjozfQ.JOmsO2Sj4xc2dHvCjDTBqZc0GC3HvkAGD15G8XAtFJQ
